# Supabase Configuration
[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[edge_runtime]
port = 54325

[auth]
external_phone_enabled = false
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_figma_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_google_enabled = false
external_kakao_enabled = false
external_keycloak_enabled = false
external_linkedin_enabled = false
external_notion_enabled = false
external_spotify_enabled = false
external_slack_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_workos_enabled = false
external_zoom_enabled = false