# Create a deployment to a remote server with FTP credentials with build.
# Run npm install and buil
name: FTP Deploy
on:
  push:
    branches:
      - main # Set a branch name to deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      NEXT_PUBLIC_GORQ_API_KEY: ${{ secrets.NEXT_PUBLIC_GORQ_API_KEY }}
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version

      - name: Clean install dependencies
        run: |
          npm cache verify || npm cache clean --force
          rm -rf node_modules
          npm ci

      - name: Build project
        run: npm run build # Adjust this command based on your build script

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }} # Set in GitHub Secrets
          username: ${{ secrets.FTP_USERNAME }} # Set in GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }} # Set in GitHub Secrets
          local-dir: ./out # Adjust based on your build output directory
          server-dir: /test # Adjust based on your server directory
